### ISSUE TITLE
npm registry type error for listener argument

### ISSUE THREAD

**Issue by martinnock** [Djelibeybi/homebridge-button-platform#1]
Issue see below log - plugin works

```
[Homebridge] [3/13/2020, 8:48:36 PM] [Button Platform] warning: npm registry: TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function. Received type object
    at checkListener (events.js:77:11)
    at ClientRequest.once (events.js:326:3)
    at new ClientRequest (_http_client.js:177:10)
    at Object.request (https.js:309:10)
    at Object.request (/home/hoobs/.hoobs/node_modules/http-proxy-agent/node_modules/agent-base/patch-core.js:25:22)
    at HttpClient.request (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/HttpClient.js:226:32)
    at HttpClient.get (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/HttpClient.js:136:17)
    at ButtonPlatform._checkLatest (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/Platform.js:380:42)
    at ButtonPlatform._heartbeat (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/Platform.js:290:12)
    at ButtonPlatform._beat (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/Platform.js:284:42)
```

(Edited for formatting)

**Comment by Djelibeybi** [comment]
@martinnock thanks for the report. This seems to be an issue with the library I'm using to check for updates. I'll double-check the upstream library to see if it's been fixed there.

**Comment by Djelibeybi** [comment]
I just pushed v1.0.3 which should resolve this warning.

**Comment by martinnock** [comment]
Thanks for now. Still having this issue with 1.0.3:

[Homebridge] [3/26/2020, 9:42:38 AM] [Button Platform] warning: npm registry: TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function. Received type object
    at checkListener (events.js:77:11)
    at ClientRequest.once (events.js:326:3)
    at new ClientRequest (_http_client.js:177:10)
    at Object.request (https.js:309:10)
    at Object.request (/home/hoobs/.hoobs/node_modules/http-proxy-agent/node_modules/agent-base/patch-core.js:25:22)
    at HttpClient.request (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/HttpClient.js:226:32)
    at HttpClient.get (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/HttpClient.js:136:17)
    at ButtonPlatform._checkLatest (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/Platform.js:380:42)
    at ButtonPlatform._heartbeat (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/Platform.js:290:12)
    at ButtonPlatform._beat (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/Platform.js:284:42)

**Comment by Djelibeybi** [comment]
@martinnock this looks like it may be a HOOBS-specific issue, becuase a default install on a vanilla instance of Homebridge doesn't include `http-proxy-agent`. I'll have to try and setup a HOOBS instance to reproduce it this weekend.

**Comment by Djelibeybi** [comment]
I've just tried to reproduce this on my end but it works just fine. I don't have a `http-proxy-agent` module installed either, so you may need to work out which of your plugins is installing that dependency.

**Comment by martinnock** [comment]
many thanks for checking. I did a couple of back and forth installation on my side and it seems to happen after installing the homebridge-fritz-platform plugin. Since I do not get this to run properly, I have deactivated it.

On another note, not part of this issue: Is there a way to get button presses "into" flic, so the opposite of what we achieve with your plugin? I desperately want to trigger the IR blaster on my hub via homekit ...

**Comment by Djelibeybi** [comment]
I've asked the Flic folks that same question but they still haven't opened up the Hub API yet, so unfortunately not. I'm going to close this issue now, but feel free to open a new one if you have any other issues or questions/suggestions.
